[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
staking_prorgam = "D8mrU8wa5qosEz17jFc5hfTmzAPemz2WGnmdbg4nTzej"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/minhbear/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
